# Generated by Django 2.0.2 on 2018-04-10 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualidadeTecnica', models.DecimalField(decimal_places=1, max_digits=1)),
                ('inovacao', models.DecimalField(decimal_places=1, max_digits=1)),
                ('resultados', models.DecimalField(decimal_places=1, max_digits=1)),
                ('metodologia', models.DecimalField(decimal_places=1, max_digits=1)),
                ('adequacaoTematicaEvento', models.DecimalField(decimal_places=1, max_digits=1)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=1)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.Artigos')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('telefone', models.CharField(max_length=25, verbose_name='telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='avaliacao.Pessoa')),
                ('curriculo', models.CharField(max_length=50, verbose_name='curriculo')),
            ],
            bases=('avaliacao.pessoa',),
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='avaliacao.Pessoa')),
                ('curriculo', models.CharField(max_length=50, verbose_name='curriculo')),
            ],
            bases=('avaliacao.pessoa',),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.Avaliador'),
        ),
        migrations.AddField(
            model_name='artigos',
            name='autores',
            field=models.ManyToManyField(to='avaliacao.Autor'),
        ),
    ]
